name: browser_headers
description: Generates randomized but response-stable "browser-like" headers.
version: 0.1.0
repository: https://github.com/csells/browser_headers
homepage: https://github.com/csells/browser_headers

environment:
  sdk: ^3.9.2

dependencies:
  http: ^1.5.0
  random_user_agents: ^1.0.17

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  test: ^1.25.6
